# Generated by Django 2.1.2 on 2018-10-07 23:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20181007_1616'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trabajador',
            name='imagen',
        ),
    ]
